compile:
	abigen --sol p2perinik.sol --pkg p2perinik --out p2perinik.go
replace:
	abigen --sol p2perinik.sol --pkg p2perinik --out p2perinik.go
	mv p2perinik.go ../src/src/p2perinik/p2perinik.go
clean:
	rm *.go
	rm ../src/src/p2perinik/*.go
